/*
 * The keybindings a practice may use, derived from the workbench's own list.
 *
 * ⛔ WHY THIS IS DERIVED IN THE WORKBENCH AND SEEDED IN THE IMAGE, which
 * looks like two places for one fact and is not.
 *
 * The removals themselves can only be COMPUTED where the workbench's default
 * keybindings are, and that is inside a running workbench:
 * `vscode://defaultsettings/keybindings.json` is a virtual document the
 * workbench generates, it is not a file in the code-server install, and
 * nothing on the host can read it. So this module derives them here.
 *
 * ⛔ But they cannot be APPLIED here. Measured on code-server 4.137.0: the
 * user keybindings file is read when a session starts, and a write to it
 * while that session is open does not take effect -- the removals sit on
 * disk, correct, and every key still fires. A session started afterwards
 * honours them completely. ⭐ So the file is seeded by the editor image's
 * entrypoint, BEFORE any session exists, and what this module does at run
 * time is REPORT: what the allow-list derives, what the session actually
 * loaded, and whether the two agree.
 *
 * ⭐ That report is the instrument that says so when the workbench gains a
 * command. The seed in the image is generated from one version of the
 * workbench; a code-server bump adds commands and keybindings to the
 * document above; the derivation moves and the seed does not; this module
 * reports `missing=<n>`, and `docker/editor/confinement.py` refuses to tag
 * the image. ⛔ Without it the seed would silently be a deny-list that was
 * right once.
 *
 * ⚠️ A REPORT IS NOT A PROOF, and this module is careful not to be read as
 * one. Comparing a derived list with a file on disk cannot see what the
 * workbench ALLOWS -- that is the Restricted Mode lesson, where a check that read
 * INSTALLATION could not see ACTIVATION. The proof is a real browser
 * pressing real keys at a real session, in `docker/editor/confinement.py`.
 * This half is the exhaustive one and that half is the behavioural one.
 */

const vscode = require('vscode');
const fs = require('fs');
const path = require('path');

const allowed = require('./allowed');

/** The workbench's own default keybindings, as a virtual document.
 *
 *  ⭐ Opening it costs no TAB: `openTextDocument` on this URI returns the
 *  document without showing it, which is why the derivation can run at
 *  activation without the reader seeing anything. */
const DEFAULTS = 'vscode://defaultsettings/keybindings.json';

/** The file the workbench reads user keybindings from, relative to the
 *  extension's own global storage.
 *
 *  ⚠️ Derived, never composed from a container path: the workbench hands
 *  every extension `globalStorageUri`, which is
 *  `<user data dir>/User/globalStorage/<extension id>`, so its grandparent
 *  is the `User` directory whatever `--user-data-dir` a consumer passed. */
const USER_KEYBINDINGS = 'keybindings.json';

/** What this module writes beside the extension's own log, for the image's gate to read. */
const DERIVED = 'keybindings.json';

function userFile(context) {
    const storage = (context.globalStorageUri && context.globalStorageUri.fsPath) || context.globalStoragePath;
    if (!storage) { return null; }
    return path.join(path.dirname(path.dirname(storage)), USER_KEYBINDINGS);
}

/** Read what the session loaded, as a list of `{key, command}`; `null` when there is no file. */
function loaded(context) {
    const file = userFile(context);
    if (!file) { return null; }
    try {
        return allowed.parse(fs.readFileSync(file, 'utf8'));
    } catch (error) {
        return error.code === 'ENOENT' ? null : undefined;
    }
}

/** A stable identity for one removal, so two lists can be compared as sets. */
function mark(entry) {
    return `${entry.key}\u0000${entry.command}`;
}

/** The command a removal takes away, or `null` for an entry that is not one. */
function removed(entry) {
    const command = entry && entry.command;
    return typeof command === 'string' && command.startsWith('-') ? command.slice(1) : null;
}

/** ⛔ THE DERIVATION IS NOT THE SAME IN EVERY SESSION, and the seed is a UNION.
 *
 *  ⚠️ Measured, and it was a surprise: the workbench's default keybinding
 *  document is not a constant. A part that has never been created contributes
 *  no keybinding, so a session that opened the Output panel lists
 *  `workbench.actions.workbench.panel.output.clearFilterText` and one that did
 *  not does not. Three entries differed between two sessions of the SAME image.
 *
 *  ⛔ A seed generated by replacing it with one session's derivation would
 *  therefore oscillate, and each regeneration would drop what another session
 *  had found. ⭐ So a regeneration UNIONS: this session's derivation, plus
 *  every removal already loaded whose command the allow-list still refuses.
 *  A removal for a key this workbench does not bind costs nothing -- the
 *  workbench ignores it -- so the union is monotonic and converges, while a
 *  command the allow-list is later WIDENED to permit drops out of it, because
 *  that is the one entry the filter does not keep.
 */
function derive(defaults, present) {
    const now = allowed.removals(defaults);
    const here = new Set(now.map(mark));
    const kept = (present || []).filter(function (entry) {
        const command = removed(entry);
        return command !== null && !allowed.allows(command) && !here.has(mark(entry));
    });
    return now.concat(kept.map(function (entry) { return { key: entry.key, command: entry.command }; }))
        .sort(function (left, right) {
            if (left.key !== right.key) { return left.key < right.key ? -1 : 1; }
            return left.command < right.command ? -1 : left.command > right.command ? 1 : 0;
        });
}

/** Compare what THIS session's workbench binds with what this session loaded.
 *
 *  ⛔ `missing` is the reading the image's gate refuses on: a removal this
 *  allow-list derives from the keybindings this workbench actually has, which
 *  the session did not load -- a key that still fires a command a practice may
 *  not use. ⭐ It is the instrument that says so when the workbench gains a
 *  command, and it is computed against the session's OWN document rather than
 *  against the seed's list, so a code-server bump is caught rather than
 *  assumed away.
 *
 *  ⚠️ `extra` is NOT "a removal this session did not derive" -- that is the
 *  ordinary case above and would be noise. It is a removal the session loaded
 *  whose command the allow-list now ALLOWS, which is the only way the seed can
 *  take something away from a practice.
 */
function compare(now, present) {
    if (!present) { return { missing: now.length, extra: 0, loaded: 0 }; }
    const here = new Set(present.map(mark));
    return {
        loaded: present.length,
        missing: now.filter(function (entry) { return !here.has(mark(entry)); }).length,
        extra: present.filter(function (entry) {
            const command = removed(entry);
            return command === null || allowed.allows(command);
        }).length,
    };
}

/** Derive the removals, write them beside the log, and answer one line of report.
 *
 *  ⛔ Never throws: a window whose log directory cannot be written is still a
 *  window whose keybindings were seeded by the image, and the confinement
 *  does not depend on this running. What depends on it is the GATE, which
 *  refuses an image whose session wrote no report at all.
 */
async function report(context, banner) {
    let defaults;
    try {
        const document = await vscode.workspace.openTextDocument(vscode.Uri.parse(DEFAULTS));
        defaults = allowed.parse(document.getText());
    } catch (error) {
        return `${banner} keybindings: the workbench's default list could not be read -- ${error && error.message}`;
    }
    const present = loaded(context);
    const now = allowed.removals(defaults);
    const seen = compare(now, present);
    try {
        const directory = (context.logUri && context.logUri.fsPath) || context.logPath;
        fs.mkdirSync(directory, { recursive: true });
        fs.writeFileSync(path.join(directory, DERIVED), `${JSON.stringify(derive(defaults, present), null, 1)}\n`);
    } catch (error) {
        /* the report line below still carries the counts */
    }
    const state = present === undefined ? 'unreadable' : present === null ? 'absent' : 'present';
    return `${banner} keybindings: derived=${now.length} loaded=${seen.loaded} ` +
        `missing=${seen.missing} extra=${seen.extra} file=${state}`;
}

module.exports = { DEFAULTS, DERIVED, USER_KEYBINDINGS, userFile, loaded, derive, compare, report };
