"""The framework pin, the installed library, and the stubs that must agree.

⛔ Generated by studyforge onboarding. A hand-edit here is a finding
against that skill rather than a fix, and a regeneration writes over it;
change corpus.json and regenerate.
"""

from __future__ import annotations

import json
import pathlib
import re


PIN = '.studyforge/pin.json'
STUBS = ['.studyforge/skills/reconnaissance.md', '.studyforge/skills/adapter.md', '.studyforge/skills/onboarding.md']
FRAMEWORK = 'studyforge'
WHERE = 'installed'
VERSION = '[0-9][0-9A-Za-z.+!_-]{0,63}'


def _root():
    """The corpus root, found from this file rather than from the cwd."""
    return pathlib.Path(__file__).resolve().parent.parent


def _pin():
    return json.loads((_root() / PIN).read_text(encoding='utf-8'))


def _installed():
    """The library this Python imports, or a sentence saying it imports none."""
    try:
        from studyforge.skills import documents
        from studyforge.skills.onboarding import library
    except ImportError:
        raise AssertionError(
            FRAMEWORK + ' is not installed in the Python running these checks; '
            'install the pinned version (docs/studyforge/ONBOARDING.md says how)'
        ) from None
    return library, documents


def test_the_pin_records_a_version_and_a_commit_and_not_a_path():
    """A pin carrying a path would carry somebody's home directory."""
    pin = _pin()
    assert pin['where'] == WHERE, 'the framework is the installed library'
    assert re.fullmatch('[0-9a-f]{40}', pin['commit']), (
        'the pin records a commit; a path is not one'
    )
    assert re.fullmatch(VERSION, pin['version']), (
        'the pin records a library version; a path is not one'
    )


def test_the_installed_library_is_the_pinned_version():
    """A pin naming a version this Python does not import points at nothing."""
    library, _documents = _installed()
    pin = _pin()
    installed = library.version()
    assert installed == pin['version'], (
        'the installed ' + FRAMEWORK + ' is ' + installed + ' and the pin names ' +
        pin['version'] + '; install the pinned version, or re-pin'
    )


def test_the_installed_library_was_built_from_the_pinned_commit():
    """A pin naming another commit than the library's own names another library."""
    library, _documents = _installed()
    built = library.commit()
    if built is None:
        skip(
            'the ' + FRAMEWORK + ' this Python imports is a source tree, '
            'not a built wheel, so it cannot say which commit it is; '
            'the version is checked'
        )
    pin = _pin()
    assert built == pin['commit'], (
        'the installed ' + FRAMEWORK + ' was built from ' + built + ' and the pin '
        'names ' + pin['commit'] + '; install the pinned build, or re-pin'
    )


def test_every_stub_names_a_skill_the_installed_library_ships():
    """A stub whose procedure the library does not ship points at nothing."""
    _library, documents = _installed()
    shipped = set(documents.names())
    named = [pathlib.PurePosixPath(where).stem for where in STUBS]
    assert [name for name in named if name not in shipped] == [], (
        'these stubs name a skill the installed library ships no procedure for'
    )


def test_no_stub_has_drifted_from_the_pin():
    """A stub naming another commit or version is a pointer that aged silently."""
    root = _root()
    pin = _pin()
    said = ('pin: ' + pin['commit'], 'version: ' + pin['version'])
    drifted = []
    for where in STUBS:
        lines = (root / where).read_text(encoding='utf-8').splitlines()
        if not all(line in lines for line in said):
            drifted.append(where)
    assert not drifted, (
        'these stubs name a commit or a version the pin does not: ' +
        repr(drifted) + '; regenerate them rather than editing them'
    )


def test_the_framework_is_not_a_submodule():
    """Nothing here is pushed, so a submodule URL has no form."""
    assert not (_root() / '.gitmodules').exists(), (
        'the framework is the installed library at a recorded version, '
        'never a submodule'
    )


class Skipped(Exception):
    """A check that cannot be read here, and why."""


def skip(why):
    """Skip this check: the runner's skip when run as a script, else pytest's."""
    if __name__ == '__main__':
        raise Skipped(why)
    try:
        import pytest
    except ImportError:
        raise Skipped(why) from None
    pytest.skip(why)


def run(checks):
    """Run every test_ function in `checks`, one line each; return the exit code."""
    failed = 0
    for name, check in sorted(checks.items()):
        if not name.startswith('test_') or not callable(check):
            continue
        try:
            check()
        except Skipped as why:
            print('skip', name, '-', why)
        except Exception as error:
            failed += 1
            print('FAIL', name, '-', type(error).__name__, error)
        else:
            print('ok', name)
    return 1 if failed else 0


if __name__ == '__main__':
    raise SystemExit(run(dict(globals())))
