package practice;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.UUID;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class EmployeeWriterTest {

    private Connection connection;

    @BeforeEach
    void openDatabase() throws SQLException {
        connection = DriverManager.getConnection("jdbc:h2:mem:" + UUID.randomUUID());
        try (Statement statement = connection.createStatement()) {
            statement.execute("CREATE TABLE employees (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "name VARCHAR(100) NOT NULL, salary DECIMAL(10,2))");
        }
    }

    @AfterEach
    void closeDatabase() throws SQLException {
        connection.close();
    }

    private String nameOf(int id) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("SELECT name FROM employees WHERE id = ?")) {
            statement.setInt(1, id);
            try (ResultSet rows = statement.executeQuery()) {
                return rows.next() ? rows.getString(1) : null;
            }
        }
    }

    private BigDecimal salaryOf(int id) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("SELECT salary FROM employees WHERE id = ?")) {
            statement.setInt(1, id);
            try (ResultSet rows = statement.executeQuery()) {
                rows.next();
                return rows.getBigDecimal(1);
            }
        }
    }

    private long rowCount() throws SQLException {
        try (Statement statement = connection.createStatement();
             ResultSet rows = statement.executeQuery("SELECT COUNT(*) FROM employees")) {
            rows.next();
            return rows.getLong(1);
        }
    }

    @Test
    void insertReturnsTheNewRowsId() throws SQLException {
        EmployeeWriter writer = new EmployeeWriter(connection);

        int ada = writer.insert("Ada", new BigDecimal("90000.00"));
        int linus = writer.insert("Linus", new BigDecimal("80000.00"));

        assertThat(nameOf(ada)).isEqualTo("Ada");
        assertThat(nameOf(linus)).isEqualTo("Linus");
        assertThat(writer.updateSalary(linus, new BigDecimal("81000.50"))).isTrue();
        assertThat(salaryOf(linus)).isEqualByComparingTo("81000.50");
    }

    @Test
    void theIdIsTheOneTheDatabaseGenerated() throws SQLException {
        EmployeeWriter writer = new EmployeeWriter(connection);
        int first = writer.insert("Ada", new BigDecimal("90000.00"));
        writer.insert("Linus", new BigDecimal("80000.00"));
        try (PreparedStatement delete = connection.prepareStatement("DELETE FROM employees WHERE id = ?")) {
            delete.setInt(1, first);
            delete.executeUpdate();
        }
        try (Statement byHand = connection.createStatement()) {
            byHand.executeUpdate("INSERT INTO employees (id, name, salary) VALUES (100, 'Barbara', 1.00), (101, 'Ken', 1.00)");
        }

        int grace = writer.insert("Grace", new BigDecimal("95000.00"));

        assertThat(grace).isEqualTo(3);
        assertThat(nameOf(grace)).isEqualTo("Grace");
    }

    @Test
    void updatingAMissingRowReturnsFalse() throws SQLException {
        EmployeeWriter writer = new EmployeeWriter(connection);
        writer.insert("Ada", new BigDecimal("90000.00"));

        assertThat(writer.updateSalary(99, new BigDecimal("1.00"))).isFalse();
    }

    @Test
    void aFailedInsertThrows() throws SQLException {
        EmployeeWriter writer = new EmployeeWriter(connection);

        assertThatThrownBy(() -> writer.insert(null, new BigDecimal("1.00"))).isInstanceOf(SQLException.class);
        assertThat(rowCount()).isZero();
    }
}
