package practice;

import java.lang.reflect.InvocationHandler;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Proxy;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class BatchInsertTest {

    private Connection connection;
    private final List<String> calls = new ArrayList<>();

    @BeforeEach
    void openDatabase() throws SQLException {
        connection = DriverManager.getConnection("jdbc:h2:mem:" + UUID.randomUUID());
        try (Statement statement = connection.createStatement()) {
            statement.execute("CREATE TABLE people (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(100))");
        }
    }

    @AfterEach
    void closeDatabase() throws SQLException {
        connection.close();
    }

    /** The real connection, with every call on it and on its statements recorded as "Type.method". */
    private Connection spied() {
        return spy(connection, Connection.class);
    }

    private <T> T spy(T target, Class<T> type) {
        InvocationHandler handler = (proxy, method, args) -> {
            calls.add(type.getSimpleName() + "." + method.getName());
            Object result;
            try {
                result = method.invoke(target, args);
            } catch (InvocationTargetException e) {
                throw e.getCause();
            }
            if (result instanceof PreparedStatement statement) {
                return spy(statement, PreparedStatement.class);
            }
            if (result instanceof ResultSet rows) {
                return spy(rows, ResultSet.class);
            }
            if (result instanceof Statement statement) {
                return spy(statement, Statement.class);
            }
            return result;
        };
        return type.cast(Proxy.newProxyInstance(type.getClassLoader(), new Class<?>[] {type}, handler));
    }

    private long count(String call) {
        return calls.stream().filter(call::equals).count();
    }

    private List<String> storedNames() throws SQLException {
        List<String> names = new ArrayList<>();
        try (Statement statement = connection.createStatement();
             ResultSet rows = statement.executeQuery("SELECT name FROM people ORDER BY id")) {
            while (rows.next()) {
                names.add(rows.getString("name"));
            }
        }
        return names;
    }

    @Test
    void insertsEveryNameAndCountsThem() throws SQLException {
        int inserted = BatchInsert.insertAll(spied(), List.of("Ada", "Linus", "Grace", "Barbara"), 2);

        assertThat(inserted).isEqualTo(4);
        assertThat(storedNames()).containsExactly("Ada", "Linus", "Grace", "Barbara");
    }

    @Test
    void sendsOneBatchPerChunk() throws SQLException {
        BatchInsert.insertAll(spied(), List.of("Ada", "Linus", "Grace", "Barbara", "Ken"), 2);

        assertThat(count("PreparedStatement.executeBatch")).isEqualTo(3);
        assertThat(count("PreparedStatement.executeUpdate")).isZero();
    }

    @Test
    void theLastPartialChunkIsSent() throws SQLException {
        int inserted = BatchInsert.insertAll(spied(), List.of("Ada", "Linus", "Grace", "Barbara", "Ken"), 2);

        assertThat(inserted).isEqualTo(5);
        assertThat(storedNames()).containsExactly("Ada", "Linus", "Grace", "Barbara", "Ken");
    }

    @Test
    void aChunkSizeBelowOneIsRefused() throws SQLException {
        assertThatThrownBy(() -> BatchInsert.insertAll(spied(), List.of("Ada"), 0))
                .isInstanceOf(IllegalArgumentException.class);
        assertThat(storedNames()).isEmpty();
    }
}
