package com.github.msorkhpar.claudejavatutor.jvminternals;

import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.util.*;
import java.util.function.Function;
import java.util.function.IntBinaryOperator;
import java.util.function.Predicate;
import java.util.stream.Collectors;

/**
 * Demonstrates bytecode execution concepts including operand stack behavior,
 * method invocation types, and bridge methods.
 */
public class BytecodeExecution {

    /**
     * Demonstrates operand stack behavior through arithmetic operations.
     * Each method corresponds to a specific bytecode pattern.
     */
    public static class OperandStackDemo {

        /**
         * Simple addition: iload_1, iload_2, iadd, ireturn
         */
        public static int add(int a, int b) {
            return a + b;
        }

        /**
         * Compound expression: demonstrates multiple stack operations.
         * Bytecode: iload_1, iload_1, imul, iconst_2, iload_1, imul, iadd, iconst_1, iadd, ireturn
         */
        public static int quadratic(int x) {
            return x * x + 2 * x + 1;
        }

        /**
         * Demonstrates local variable usage with the operand stack.
         */
        public static int swapAndCompute(int a, int b) {
            int temp = a;
            a = b;
            b = temp;
            return a - b;
        }

        /**
         * Demonstrates long arithmetic (uses two stack slots per value).
         */
        public static long longAdd(long a, long b) {
            return a + b;
        }

        /**
         * Demonstrates mixed-type arithmetic with type conversion.
         * Involves i2d (int-to-double) conversion in bytecode.
         */
        public static double mixedArithmetic(int intVal, double doubleVal) {
            return intVal + doubleVal;
        }

        /**
         * Demonstrates boolean operations in bytecode (booleans are ints internally).
         */
        public static boolean logicalOps(boolean a, boolean b) {
            return a && b || !a;
        }
    }

    /**
     * Demonstrates different method invocation types in bytecode.
     */
    public static class MethodInvocationDemo {

        /**
         * Instance method -- invoked via invokevirtual
         */
        public String virtualMethod() {
            return "invokevirtual";
        }

        /**
         * Static method -- invoked via invokestatic
         */
        public static String staticMethod() {
            return "invokestatic";
        }

        /**
         * Private method -- invoked via invokespecial
         */
        private String specialMethod() {
            return "invokespecial";
        }

        /**
         * Calls all method invocation types and returns their results.
         */
        public Map<String, String> demonstrateAllInvocations() {
            Map<String, String> results = new LinkedHashMap<>();

            // invokevirtual: virtual instance method call
            results.put("virtual", this.virtualMethod());

            // invokestatic: static method call
            results.put("static", MethodInvocationDemo.staticMethod());

            // invokespecial: private method call
            results.put("special", this.specialMethod());

            // invokeinterface: interface method call
            List<String> list = new ArrayList<>();
            list.add("invokeinterface");
            results.put("interface", list.get(0));

            // invokedynamic: lambda expression
            Function<String, String> lambda = s -> s.toUpperCase();
            results.put("dynamic", lambda.apply("invokedynamic"));

            return results;
        }

        /**
         * Demonstrates constructor invocation -- invokespecial for <init>
         */
        public Object createObject() {
            return new Object(); // new + invokespecial Object.<init>
        }
    }

    /**
     * Demonstrates bridge methods generated by the compiler.
     */
    public interface Transformer<T> {
        T transform(T input);
    }

    public static class StringTransformer implements Transformer<String> {
        @Override
        public String transform(String input) {
            return input != null ? input.toUpperCase() : null;
        }
    }

    public static class IntegerTransformer implements Transformer<Integer> {
        @Override
        public Integer transform(Integer input) {
            return input != null ? input * 2 : null;
        }
    }

    /**
     * Utility class for inspecting bridge methods via reflection.
     */
    public static class BridgeMethodInspector {

        /**
         * Returns the names of bridge methods in a given class.
         */
        public List<String> findBridgeMethods(Class<?> clazz) {
            return Arrays.stream(clazz.getDeclaredMethods())
                    .filter(Method::isBridge)
                    .map(m -> m.getName() + "(" +
                            Arrays.stream(m.getParameterTypes())
                                    .map(Class::getSimpleName)
                                    .collect(Collectors.joining(", ")) + ")")
                    .collect(Collectors.toList());
        }

        /**
         * Returns the names of synthetic methods in a given class.
         */
        public List<String> findSyntheticMethods(Class<?> clazz) {
            return Arrays.stream(clazz.getDeclaredMethods())
                    .filter(Method::isSynthetic)
                    .map(m -> m.getName() + "(" +
                            Arrays.stream(m.getParameterTypes())
                                    .map(Class::getSimpleName)
                                    .collect(Collectors.joining(", ")) + ")")
                    .collect(Collectors.toList());
        }

        /**
         * Counts the total number of methods (including bridge/synthetic) in a class.
         */
        public int countAllMethods(Class<?> clazz) {
            return clazz.getDeclaredMethods().length;
        }

        /**
         * Counts only non-bridge, non-synthetic methods.
         */
        public int countUserMethods(Class<?> clazz) {
            return (int) Arrays.stream(clazz.getDeclaredMethods())
                    .filter(m -> !m.isBridge() && !m.isSynthetic())
                    .count();
        }
    }

    /**
     * Demonstrates autoboxing/unboxing behavior in bytecode.
     * Autoboxing uses invokestatic Integer.valueOf() and
     * unboxing uses invokevirtual Integer.intValue().
     */
    public static class AutoboxingDemo {

        /**
         * Demonstrates autoboxing (int -> Integer via Integer.valueOf).
         */
        public Integer autobox(int value) {
            return value; // Bytecode: invokestatic Integer.valueOf(int)
        }

        /**
         * Demonstrates unboxing (Integer -> int via Integer.intValue).
         */
        public int unbox(Integer value) {
            return value; // Bytecode: invokevirtual Integer.intValue()
        }

        /**
         * Demonstrates the Integer cache (-128 to 127).
         * Integer.valueOf uses a cache for values in this range.
         */
        public boolean isCached(int value) {
            Integer a = value;
            Integer b = value;
            return a == b; // True for -128 to 127 due to Integer cache
        }

        /**
         * Shows that arithmetic on Integer objects involves boxing/unboxing.
         */
        public Integer addBoxed(Integer a, Integer b) {
            return a + b; // Bytecode: unbox both, iadd, box result
        }
    }

    /**
     * Demonstrates constant pool concepts.
     */
    public static class ConstantPoolDemo {

        /**
         * String literals are stored in the constant pool and interned.
         */
        public boolean stringInternDemo(String input) {
            String literal = "hello";
            String interned = input.intern();
            return literal == interned; // True if input equals "hello"
        }

        /**
         * Demonstrates that compile-time constants are inlined by the compiler.
         */
        public static final int COMPILE_TIME_CONSTANT = 42;
        public static final String STRING_CONSTANT = "constant";

        /**
         * Returns the constant. In bytecode, this is loaded directly from the
         * constant pool (ldc instruction), not via a field access.
         */
        public int getConstant() {
            return COMPILE_TIME_CONSTANT; // Bytecode: bipush 42
        }

        /**
         * Demonstrates that non-compile-time constants use field access.
         */
        public static final int RUNTIME_CONSTANT = Integer.parseInt("42");

        public int getRuntimeConstant() {
            return RUNTIME_CONSTANT; // Bytecode: getstatic (field access required)
        }
    }

    /**
     * Demonstrates lambda desugaring in bytecode.
     * Lambda bodies become private methods, and invokedynamic creates the wrapper.
     */
    public static class LambdaDesugaringDemo {

        /**
         * Non-capturing lambda: can be a singleton (no per-call allocation).
         */
        public IntBinaryOperator getNonCapturingLambda() {
            return (a, b) -> a + b;
        }

        /**
         * Capturing lambda: must create a new instance to capture the variable.
         */
        public Predicate<Integer> getCapturingLambda(int threshold) {
            return n -> n > threshold; // Captures 'threshold'
        }

        /**
         * Method reference: similar to non-capturing lambda in bytecode.
         */
        public Function<String, Integer> getMethodReference() {
            return Integer::parseInt;
        }

        /**
         * Verifies that non-capturing lambdas can be reused (same instance).
         */
        public boolean nonCapturingLambdaReuse() {
            IntBinaryOperator a = getNonCapturingLambda();
            IntBinaryOperator b = getNonCapturingLambda();
            // JVM MAY return the same instance for non-capturing lambdas
            // This is implementation-dependent, so we just verify they work the same
            return a.applyAsInt(2, 3) == b.applyAsInt(2, 3);
        }
    }
}
